name: Frontend prod CI

on:
  push:
    paths:
      - "frontend/**"
    tags:
      - 'v*'
  pull_request:
    types:
      - opened
      - reopened
    paths:
      - "frontend/**"
    branches:
      - 'main'
      - 'dev'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Goto frontend and run tests
        run: cd frontend && npm i && npm test
  docker:
    needs: 
      - test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: lukaszgrzegorzewski/renthub_backend-ci
      - 
        name: Debug meta
        run:  echo "Tags => ${{ steps.meta.outputs.tags }}"

      - 
        uses: haya14busa/action-cond@v1
        name: Tag or Sha
        id: tag_sha
        with:
          cond: ${{ steps.meta.outputs.tags != '***/front:main' }}
          if_true: ${{ steps.meta.outputs.tags }}
          if_false: "renthub/front:${{github.sha}}"

      - 
        name: Use conditional value
        run: echo "tag_sha => ${{ steps.tag_sha.outputs.value }}"

      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          target: prod
          platforms: linux/amd64, linux/arm64, linux/386
          push: true
          tags: ${{ steps.meta.outputs.tags }}
