name: Frontend dev CI

on:
  push:
    branches:
      - dev
    tags:
      - 'd*'

jobs:
  docker:
    if: github.ref_type == 'tag' && github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/tags/d')
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: renthub/front
      - 
        name: Debug meta
        run:  echo "Tags => ${{ steps.meta.outputs.tags }}"
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          target: dev
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
